env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
rules: {
  linebreak-style: ["error", "unix"],
  quotes: ["error", "double"],
  no-console: 0 , #["error", { allow: ["warn", "error", "log"] }]
  indent: ["error", 2],  #["error", { "code": 80 }]
  no-use-before-define: ["error", { "functions": false, "classes": false, "variables": true }] #["error", { "functions": true, "classes": true, "variables": true }]
}
